apiVersion: v1
kind: Pod
metadata:
  name: gitpod-helm-installer
spec:
    containers:
      - name: gitpod-helm-installer
        image: alpine/helm:3.2.4
        volumeMounts:
          - name: kubeconfig
            mountPath: /root/.kube/config
          - name: installfiles
            mountPath: /root/install
        command: ["sh", "/root/install/command.sh"]
    volumes:
      - name: kubeconfig
        hostPath:
          path: /etc/rancher/k3s/k3s_.yaml
      - name: installfiles
        configMap:
          name: gitpod-helm-installer
    restartPolicy: OnFailure

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gitpod-helm-installer
data:
  command.sh: |-
    #!/bin/sh
    set -eux
    helm repo add gitpod https://charts.gitpod.io
    helm repo update
    helm install gitpod gitpod/gitpod --version=0.8.0 --timeout 60m --values /root/install/values.yaml
  values.yaml: |-
    certificatesSecret:
      secretName: proxy-config-certificates

    components:
      wsDaemon:
        containerRuntime:
          nodeRoots:
          - /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io
      wsManagerNode:
        containerdSocket: /run/k3s/containerd/containerd.sock
      workspace:
        template:
          spec:
            dnsConfig: null
            dnsPolicy: ClusterFirst

    installPodSecurityPolicies: true
    
    minio:
      accessKey: minio
      secretKey: minio1234
